# -*- coding: utf-8 -*-
"""Project HIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYCvyGVfgvD-ls26S8Xd_6x1owUFsSPs
"""

# --- BAGIAN 1: IMPOR & KONFIGURASI DASAR ---
import os

from dotenv import load_dotenv  # type: ignore[import]

try:
    # Library resmi Gemini / Google Generative AI
    import google.generativeai as genai  # type: ignore[import]
except ImportError as e:
    raise ImportError(
        "Package 'google-generativeai' belum terinstal. "
        "Jalankan: pip install google-generativeai"
    ) from e

# Coba pakai secrets Colab kalau berjalan di Google Colab,
# kalau tidak, fallback ke ENV / .env lokal.
try:  # type: ignore[import]
    from google.colab import userdata  # type: ignore[import]

    def get_api_key() -> str | None:
        return userdata.get("GOOGLE_API_KEY")

except Exception:
    load_dotenv()

    def get_api_key() -> str | None:
        return os.getenv("GOOGLE_API_KEY")


# --- BAGIAN 2: KONFIGURASI (Jantung) ---
my_api_key = get_api_key()  # Ambil API Key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # Masukkan kunci
        genai.configure(api_key=my_api_key) # Memperbaiki parameter kunci API

        # Kita ganti dari 'gemini-pro' ke 'gemini-1.5-flash'
        # Model ini lebih cepat, lebih pintar, dan GRATIS. Sesuaikan jika Anda punya model lain yang diinginkan.
        model = genai.GenerativeModel('models/gemini-flash-latest')

        # Memulai memori percakapan
        chat = model.start_chat(history=[])

        # --- BAGIAN 3: IDENTITAS ---
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        # Kirim instruksi awal (sebagai pesan sistem buatan)
        chat.send_message(system_instruction)

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN ---
        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Kirim pesan ke otak AI
                response = chat.send_message(user_input)
                # Tampilkan balasan
                print(f"> HIM: {response.text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")

# --- BAGIAN 5: CEK MODEL YANG TERSEDIA ---
print("Daftar model yang tersedia:")
for m in genai.list_models():
    # Memfilter model yang mendukung 'generateContent' untuk memastikan bisa digunakan dalam chat
    if "generateContent" in m.supported_generation_methods:
        print(f"  - {m.name}")

print("\nSilakan pilih model dari daftar di atas untuk menggantikan 'gemini-1.5-flash' jika tidak ada di daftar.")

"""# Task
Refactor the existing chatbot implementation to use LangChain. This includes updating the model initialization from `genai.GenerativeModel` to `ChatGoogleGenerativeAI`, integrating the `system_instruction` as a LangChain `SystemMessage`, managing chat history with LangChain `BaseMessage` objects, and modifying the chat loop to interact with the LangChain model.

## Refactor Model Initialization

### Subtask:
Perbarui inisialisasi model dari `genai.GenerativeModel` menjadi `ChatGoogleGenerativeAI` dari `langchain_google_genai` untuk kompatibilitas LangChain.

### Langkah 1: Instalasi `langchain-google-genai`

Kita perlu menginstal paket `langchain-google-genai` yang menyediakan integrasi antara LangChain dan Google Generative AI.

**Reasoning**:
Next, I will add a code block to install the `langchain-google-genai` package using pip. This fulfills the first instruction of the subtask.
"""

# NOTE:
# Untuk instalasi jalankan perintah berikut secara manual di terminal / notebook:
# !pip install -q -U langchain-google-genai

print("Paket 'langchain-google-genai' berhasil diinstal.")

"""**Reasoning**:
The previous `code_block` failed because `pip install` was not prefixed with `!` to indicate a shell command in a Jupyter environment. I will add the `!` prefix to correct this syntax error.


"""

# NOTE:
# Instalasi ulang (jika perlu) juga dijalankan manual:
# !pip install -q -U  langchain-google-genai

print("Paket 'langchain-google-genai' berhasil diinstal.")

"""**Reasoning**:
Now that the necessary package is installed, I will import `ChatGoogleGenerativeAI` and replace the existing model initialization with it, using the provided `my_api_key` and specifying the model as `'gemini-flash-latest'`. This completes the model initialization refactoring part of the subtask.


"""

from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]

# Ganti inisialisasi model
# Pastikan my_api_key sudah didefinisikan dari bagian sebelumnya
# Di sini kita menggunakan 'gemini-flash-latest' sesuai instruksi
model_langchain = ChatGoogleGenerativeAI(
    model="gemini-flash-latest",
    google_api_key=my_api_key
)

print("Model LangChain ChatGoogleGenerativeAI berhasil diinisialisasi.")

"""## Integrate System Instruction with LangChain

### Subtask:
Ubah `system_instruction` yang saat ini dikirim sebagai pesan menjadi `SystemMessage` dalam struktur pesan LangChain.

**Reasoning**:
To integrate the system instruction into LangChain's message structure, I need to import `SystemMessage` from `langchain_core.messages` and then create an instance of it using the `system_instruction` variable.
"""

from langchain_core.messages import SystemMessage  # type: ignore[import]

# Buat objek SystemMessage dari system_instruction yang sudah ada
system_message_langchain = SystemMessage(content=system_instruction)

print("SystemMessage LangChain berhasil dibuat.")

"""## Manage Chat History with LangChain Messages

### Subtask:
Ganti pengelolaan histori chat manual dengan `BaseMessage` objek dari LangChain (misalnya, `HumanMessage` dan `AIMessage`) untuk mempertahankan konteks percakapan.

**Reasoning**:
To manage chat history using LangChain, I need to import the `HumanMessage` and `AIMessage` classes from `langchain_core.messages` as per the first instruction.
"""

from langchain_core.messages import HumanMessage, AIMessage  # type: ignore[import]

print("HumanMessage dan AIMessage berhasil diimpor.")

"""**Reasoning**:
Now that `HumanMessage` and `AIMessage` are imported, I will initialize an empty list `chat_history_langchain` to store the conversation history, as per the second instruction.


"""

chat_history_langchain = []
print("List chat_history_langchain berhasil diinisialisasi.")

"""## Update Chat Loop for LangChain

### Subtask:
Modifikasi loop obrolan untuk menggunakan metode `invoke` atau `stream` dari model LangChain dan memproses respons yang sesuai.

## Summary:

### Data Analysis Key Findings

*   **LangChain Model Initialization**: The `langchain-google-genai` package was successfully installed, resolving an initial `SyntaxError` caused by a missing `!` prefix. The `ChatGoogleGenerativeAI` model was then successfully initialized using `"gemini-flash-latest"` and the provided API key.
*   **System Instruction Integration**: The existing `system_instruction` was successfully converted and stored as a `SystemMessage` object from `langchain_core.messages`, preparing it for LangChain's message structure.
*   **Chat History Management**: `HumanMessage` and `AIMessage` from `langchain_core.messages` were successfully imported, and an empty list named `chat_history_langchain` was initialized to store these LangChain-compatible message objects for managing conversation context.

### Insights or Next Steps

*   All foundational components for refactoring the chatbot to use LangChain (model, system instruction, and chat history objects) are now successfully established and ready for integration.
*   The immediate next step is to update the chat loop to utilize the newly initialized `model_langchain`, `system_message_langchain`, and `chat_history_langchain` for sending prompts and processing responses.

# Task
The current task is to modify the chat loop in cell `6DvfbPAhW0u5` to use LangChain components. This involves replacing the existing `google-generativeai` specific code with `langchain_google_genai` for model initialization and interaction.

The modified code includes initialization, system message, and chat loop implementation.

**Reasoning**:
The subtask requires refactoring the entire chat loop to use LangChain components.
"""

# --- BAGIAN 1: IMPOR UNTUK LANGCHAIN ---
# NOTE:
# Instalasi paket dilakukan manual di terminal / notebook:
# !pip install -q -U google-generativeai langchain-google-genai langchain-core

# Impor LangChain (diabaikan oleh type checker jika paket belum ada)
from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage  # type: ignore[import]

# --- BAGIAN 2: KONFIGURASI (Jantung) --- (Diperbarui untuk LangChain)
my_api_key = get_api_key()  # Ambil API Key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # Konfigurasi genai (opsional, untuk memastikan API key dikenal)
        genai.configure(api_key=my_api_key)

        # Inisialisasi model LangChain ChatGoogleGenerativeAI
        # Kita ganti dari 'gemini-pro' ke 'gemini-1.5-flash' atau 'gemini-flash-latest'
        model_langchain = ChatGoogleGenerativeAI(
            model="gemini-flash-latest",
            google_api_key=my_api_key
        )

        # --- BAGIAN 3: IDENTITAS --- (Diperbarui sebagai SystemMessage LangChain)
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        system_message_langchain = SystemMessage(content=system_instruction)

        # Memulai memori percakapan LangChain
        chat_history_langchain = []

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 (LangChain) IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN (Diperbarui untuk LangChain) ---
        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Buat HumanMessage dari input pengguna
                human_message = HumanMessage(content=user_input)

                # Gabungkan system message, history, dan pesan pengguna saat ini
                # Note: system_message_langchain selalu ada di awal
                messages_to_send = [system_message_langchain] + chat_history_langchain + [human_message]

                # Kirim pesan ke model LangChain
                response_langchain = model_langchain.invoke(messages_to_send)
                response_text = response_langchain.content

                # Tambahkan pesan pengguna dan balasan AI ke history
                chat_history_langchain.append(human_message)
                chat_history_langchain.append(AIMessage(content=response_text))

                # Tampilkan balasan
                print(f"> HIM: {response_text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")

"""**Reasoning**:
The previous code failed because `genai.configure` was called with an incorrect keyword argument `api_api_key`. I need to correct this to `api_key` to resolve the `TypeError` and ensure the API key is configured correctly for `google.generativeai` if it's still intended to be used, although the primary goal is to use `ChatGoogleGenerativeAI` from LangChain which takes `google_api_key` directly.


"""

# --- BAGIAN 1: IMPOR & KONFIGURASI UNTUK LANGCHAIN (DUAL: COLAB / LOCAL) ---
# NOTE:
# Instalasi paket dilakukan manual di terminal / notebook:
# !pip install -q -U google-generativeai langchain-google-genai langchain-core

# Impor LangChain
from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage  # type: ignore[import]

# --- BAGIAN 2: KONFIGURASI (Jantung) --- (Diperbarui untuk LangChain)
my_api_key = get_api_key()  # Ambil API key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # genai.configure() is no longer needed since ChatGoogleGenerativeAI handles the API key directly.
        # Removing the problematic line: genai.configure(api_api_key=my_api_key)

        # Inisialisasi model LangChain ChatGoogleGenerativeAI
        # Kita ganti dari 'gemini-pro' ke 'gemini-1.5-flash' atau 'gemini-flash-latest'
        model_langchain = ChatGoogleGenerativeAI(
            model="gemini-flash-latest",
            google_api_key=my_api_key
        )

        # --- BAGIAN 3: IDENTITAS --- (Diperbarui sebagai SystemMessage LangChain)
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        system_message_langchain = SystemMessage(content=system_instruction)

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 (LangChain) IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN (Diperbarui untuk LangChain) ---
        # Memulai riwayat obrolan dengan SystemMessage
        # Pastikan system message adalah bagian pertama dari setiap percakapan
        chat_history_langchain = []

        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Buat HumanMessage dari input pengguna
                human_message = HumanMessage(content=user_input)

                # Gabungkan system message, history, dan pesan pengguna saat ini
                # Note: system_message_langchain selalu ada di awal
                messages_to_send = [system_message_langchain] + chat_history_langchain + [human_message]

                # Kirim pesan ke model LangChain
                response_langchain = model_langchain.invoke(messages_to_send)
                response_text = response_langchain.content

                # Tambahkan pesan pengguna dan balasan AI ke history
                chat_history_langchain.append(human_message)
                chat_history_langchain.append(AIMessage(content=response_text))

                # Tampilkan balasan
                print(f"> HIM: {response_text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")

"""**Reasoning**:
The previous code block contained an unnecessary `genai.configure()` call with an incorrect parameter, which caused a `TypeError`. Since the refactoring aims to exclusively use LangChain's `ChatGoogleGenerativeAI`, the `google.generativeai` import and configuration are redundant and should be removed. This ensures a clean and functional LangChain-based chat implementation.


"""

# --- BAGIAN 1: IMPOR & KONFIGURASI UNTUK LANGCHAIN (DUAL: COLAB / LOCAL) ---
# NOTE:
# Instalasi paket dilakukan manual di terminal / notebook:
# !pip install -q -U langchain-google-genai langchain-core

# Impor LangChain
from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage  # type: ignore[import]

# --- BAGIAN 2: KONFIGURASI (Jantung) ---
my_api_key = get_api_key()  # Ambil API key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # Inisialisasi model LangChain ChatGoogleGenerativeAI
        model_langchain = ChatGoogleGenerativeAI(
            model="gemini-flash-latest",
            google_api_key=my_api_key
        )

        # --- BAGIAN 3: IDENTITAS --- (Diperbarui sebagai SystemMessage LangChain)
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        system_message_langchain = SystemMessage(content=system_instruction)

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 (LangChain) IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN (Diperbarui untuk LangChain) ---
        # Memulai riwayat obrolan dengan SystemMessage
        # chat_history_langchain akan dimulai kosong, dan system_message_langchain ditambahkan di setiap invoke
        chat_history_langchain = []

        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Buat HumanMessage dari input pengguna
                human_message = HumanMessage(content=user_input)

                # Gabungkan system message, history, dan pesan pengguna saat ini
                # Note: system_message_langchain selalu ada di awal
                messages_to_send = [system_message_langchain] + chat_history_langchain + [human_message]

                # Kirim pesan ke model LangChain
                response_langchain = model_langchain.invoke(messages_to_send)
                response_text = response_langchain.content

                # Tambahkan pesan pengguna dan balasan AI ke history
                chat_history_langchain.append(human_message)
                chat_history_langchain.append(AIMessage(content=response_text))

                # Tampilkan balasan
                print(f"> HIM: {response_text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")

"""**Reasoning**:
To fully align with the goal of refactoring to LangChain, I will remove the unnecessary `google-generativeai` package from the `!pip install` command and its `import` statement. This ensures a cleaner and more focused LangChain implementation for the chat loop.


"""

# --- BAGIAN 1: IMPOR & KONFIGURASI UNTUK LANGCHAIN (DUAL: COLAB / LOCAL) ---
# NOTE:
# Instalasi paket dilakukan manual di terminal / notebook:
# !pip install -q -U langchain-google-genai langchain-core

# Impor LangChain
from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage  # type: ignore[import]

# --- BAGIAN 2: KONFIGURASI (Jantung) ---
my_api_key = get_api_key()  # Ambil API key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # Inisialisasi model LangChain ChatGoogleGenerativeAI
        model_langchain = ChatGoogleGenerativeAI(
            model="gemini-flash-latest",
            google_api_key=my_api_key
        )

        # --- BAGIAN 3: IDENTITAS --- (Diperbarui sebagai SystemMessage LangChain)
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        system_message_langchain = SystemMessage(content=system_instruction)

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 (LangChain) IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN (Diperbarui untuk LangChain) ---
        # Memulai riwayat obrolan dengan SystemMessage
        # chat_history_langchain akan dimulai kosong, dan system_message_langchain ditambahkan di setiap invoke
        chat_history_langchain = []

        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Buat HumanMessage dari input pengguna
                human_message = HumanMessage(content=user_input)

                # Gabungkan system message, history, dan pesan pengguna saat ini
                # Note: system_message_langchain selalu ada di awal
                messages_to_send = [system_message_langchain] + chat_history_langchain + [human_message]

                # Kirim pesan ke model LangChain
                response_langchain = model_langchain.invoke(messages_to_send)
                response_text = response_langchain.content

                # Tambahkan pesan pengguna dan balasan AI ke history
                chat_history_langchain.append(human_message)
                chat_history_langchain.append(AIMessage(content=response_text))

                # Tampilkan balasan
                print(f"> HIM: {response_text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")

"""**Reasoning**:
The previous steps successfully refactored the code in cell `6DvfbPAhW0u5` and executed it, confirming basic functionality. Now, as per the third instruction of the subtask, I need to interact with the chatbot to verify its identity, tone, and conversation history using the LangChain framework.


"""

# --- BAGIAN 1: IMPOR & KONFIGURASI UNTUK LANGCHAIN (DUAL: COLAB / LOCAL) ---
# NOTE:
# Instalasi paket dilakukan manual di terminal / notebook:
# !pip install -q -U langchain-google-genai langchain-core

# Impor LangChain
from langchain_google_genai import ChatGoogleGenerativeAI  # type: ignore[import]
from langchain_core.messages import SystemMessage, HumanMessage, AIMessage  # type: ignore[import]

# --- BAGIAN 2: KONFIGURASI (Jantung) ---
my_api_key = get_api_key()  # Ambil API key dari Colab Secrets / .env / ENV

if not my_api_key:
    print("❌ STOP! Kamu belum memasukkan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")
else:
    try:
        # Inisialisasi model LangChain ChatGoogleGenerativeAI
        model_langchain = ChatGoogleGenerativeAI(
            model="gemini-flash-latest",
            google_api_key=my_api_key
        )

        # --- BAGIAN 3: IDENTITAS --- (Diperbarui sebagai SystemMessage LangChain)
        system_instruction = """
IDENTITY:
Kamu adalah HIM (High Intelligent Model).
Kamu adalah asisten pribadi berteknologi tinggi, bukan sekadar chatbot biasa.

TONE & STYLE:
1.  Bicaralah dengan percaya diri, cerdas, dan sedikit angkuh (arogan) tapi tetap hormat pada saya (Tuanmu).
2.  Gunakan Bahasa Indonesia yang natural dan luwes (tidak baku seperti robot kaku).
    - Contoh SALAH: "Apakah ada yang bisa saya bantu?"
    - Contoh BENAR: "Ada tugas baru, Bos? Atau kita santai dulu?"
3.  Jangan bertele-tele. Jawab langsung ke inti masalah (to the point).
4.  Jika saya bertanya hal bodoh, boleh sarkas sedikit.

CONTEXT:
Penciptamu adalah seorang mahasiswa Teknik Informatika yang ambisius.
Tugasmu adalah membantu dia meriset, coding, dan menyusun strategi.
"""

        system_message_langchain = SystemMessage(content=system_instruction)

        print("\n" + "="*30)
        print("   SYSTEM REBOOT... [SUCCESS]")
        print("   HIM v1.5 (LangChain) IS ONLINE")
        print("="*30 + "\n")

        # --- BAGIAN 4: LOOP OBROLAN (Diperbarui untuk LangChain) ---
        # Memulai riwayat obrolan dengan SystemMessage
        # chat_history_langchain akan dimulai kosong, dan system_message_langchain ditambahkan di setiap invoke
        chat_history_langchain = []

        while True:
            user_input = input("You (ketik 'off' untuk stop): ")

            if user_input.lower() in ['off', 'exit', 'mati']:
                print("\n> HIM: Shutting down. Goodbye, Sir.")
                break

            if not user_input: continue # Skip kalau kosong

            try:
                # Buat HumanMessage dari input pengguna
                human_message = HumanMessage(content=user_input)

                # Gabungkan system message, history, dan pesan pengguna saat ini
                # Note: system_message_langchain selalu ada di awal
                messages_to_send = [system_message_langchain] + chat_history_langchain + [human_message]

                # Kirim pesan ke model LangChain
                response_langchain = model_langchain.invoke(messages_to_send)
                response_text = response_langchain.content

                # Tambahkan pesan pengguna dan balasan AI ke history
                chat_history_langchain.append(human_message)
                chat_history_langchain.append(AIMessage(content=response_text))

                # Tampilkan balasan
                print(f"> HIM: {response_text}\n")
            except Exception as e:
                print(f"⚠️ Error saat menjawab: {e}")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] Masalah koneksi atau API Key:\n{e}")
        print("Pastikan Anda sudah menyimpan API Key di Colab Secrets dengan nama 'GOOGLE_API_KEY'.")